SUMMARY = "WiseKiosk frontend: the static bundle the kiosk displays"
DESCRIPTION = "A Svelte single-page bundle, generated by vite from the app's own source. There is \
no runtime here -- the output is HTML, JS, CSS and a font, served by wisekiosk-backend out of \
/srv/kiosk. Built from source rather than consumed as an artifact from the app's CI because it is \
a static-site generator: the inputs are pinned and the output is a directory of files."

require wisekiosk-src.inc

LIC_FILES_CHKSUM = "file://LICENSE;md5=4af5bdd6287d36bddd2161cdad4e1eb5"

# `;dev=1`: every package in the shrinkwrap is a devDependency, vite included,
# and the closure resolves empty without it. The npmsw path is literal, not
# searched through FILESPATH. destsuffix puts node_modules beside the app's
# package.json at git/frontend, where node resolves imports by walking up.
SRC_URI += "npmsw://${THISDIR}/${BPN}/npm-shrinkwrap.json;dev=1;destsuffix=git/frontend"

# Build-host only, and no `inherit npm`: npmsw places the closure and the
# deliverable is the emitted bundle, not a target module.
DEPENDS = "nodejs-binary-native"

S = "${WORKDIR}/git"

do_compile() {
    cd ${S}/frontend
    node node_modules/vite/bin/vite.js build
}

do_install() {
    install -d ${D}/srv/kiosk
    cp -R --no-dereference --preserve=mode,timestamps ${S}/frontend/dist/. ${D}/srv/kiosk/

    # Site configuration, not baked. The backend serves this tree per request
    # through http.Dir, which follows the link, so a file written to /data later
    # needs no restart and a dangling link is a 404.
    ln -s /data/config/config.json ${D}/srv/kiosk/config.json
}

FILES:${PN} = "/srv/kiosk"
