SUMMARY = "WiseKiosk frontend: the static bundle the kiosk displays"
DESCRIPTION = "A Svelte single-page bundle, generated by vite from the app's own source. There is \
no runtime here -- the output is HTML, JS, CSS and a font, served by wisekiosk-backend out of \
/srv/kiosk. Built from source rather than consumed as an artifact from the app's CI because it is \
a static-site generator: the inputs are pinned and the output is a directory of files."

require wisekiosk-src.inc

LIC_FILES_CHKSUM = "file://LICENSE;md5=4af5bdd6287d36bddd2161cdad4e1eb5"

# `;dev=1` is mandatory, not a preference: all 260 packages in the shrinkwrap
# are devDependencies -- vite, svelte, typescript and ajv included -- so the
# fetcher resolves an EMPTY closure without it and the failure surfaces much
# later as a missing tool. The URL path is literal, not searched through
# FILESPATH, which is why the shrinkwrap sits at ${THISDIR}/${BPN}/ (poky's own
# npm documentation uses this layout).
#
# destsuffix puts node_modules beside the app's package.json. The git fetch
# lands at ${WORKDIR}/git and the frontend package root is git/frontend, so
# node resolves imports by walking up from there as it would in a checkout.
SRC_URI += "npmsw://${THISDIR}/${BPN}/npm-shrinkwrap.json;dev=1;destsuffix=git/frontend"

# Node is a build-host tool and never reaches the device; see the recipe.
# NOT `inherit npm`: that class packages one npm module for the target and
# wants npm to run an install. What is wanted here is the opposite -- npmsw has
# already placed the closure, and the deliverable is the emitted bundle, not
# the module.
DEPENDS = "nodejs-binary-native"

S = "${WORKDIR}/git"

# npmsw does not run lifecycle scripts, and nothing here needs one. esbuild's
# postinstall only swaps its JS shim for the platform binary as an
# optimisation, and fsevents is macOS-only.
do_compile() {
    cd ${S}/frontend
    node node_modules/vite/bin/vite.js build
}

# The bundle is data. /srv/kiosk matches the path the app's own container
# serves from, so -static-root reads the same in both places.
do_install() {
    install -d ${D}/srv/kiosk
    cp -R --no-dereference --preserve=mode,timestamps ${S}/frontend/dist/. ${D}/srv/kiosk/
}

FILES:${PN} = "/srv/kiosk"
