SUMMARY = "Node.js (upstream binary, build host only)"
DESCRIPTION = "The frontend bundle is generated by vite, which runs on node. Node is a BUILD-HOST \
tool here and never reaches the device: upstream dropped ARMv6 after v12, and the kiosk serves \
static files. meta-openembedded ships nodejs 20.20.2 against the app's declared 24, and building \
node from source costs an hour to produce a compiler for HTML -- so this unpacks the official \
tarball the way poky's go-binary-native does, and is a native recipe only."
HOMEPAGE = "https://nodejs.org/"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://LICENSE;md5=edc0683b77d2c503217642fa000b5b31"

# No PROVIDES = "nodejs-native": meta-oe already provides it, and a second
# provider needs a PREFERRED_PROVIDER. Consumers name this recipe in DEPENDS.

# Upstream names the arch x64/arm64 where Yocto says x86_64/aarch64. An unlisted
# host falls through to its own name, which has no checksum below.
def node_build_arch(d):
    arch = d.getVar("BUILD_ARCH")
    return {"x86_64": "x64", "aarch64": "arm64"}.get(arch, arch)

NODE_BUILD_ARCH = "${@node_build_arch(d)}"

# Checksums at https://nodejs.org/dist/v${PV}/SHASUMS256.txt
SRC_URI = "https://nodejs.org/dist/v${PV}/node-v${PV}-linux-${NODE_BUILD_ARCH}.tar.xz;name=linux_${NODE_BUILD_ARCH}"
SRC_URI[linux_x64.sha256sum] = "2f2c0da162318f0de47665410c7c8c2ed3d36c8f3105de4bbc61176c70a7cbf2"
SRC_URI[linux_arm64.sha256sum] = "5f4ddab610c1ab2016b3c227cebdbf6d9495161487e4739c7b90090595f465f7"

# Held to the major the app's engines field declares.
UPSTREAM_CHECK_URI = "https://nodejs.org/dist/"
UPSTREAM_CHECK_REGEX = "v(?P<pver>24(\.\d+)+)/"

CVE_PRODUCT = "nodejs:node.js"

S = "${WORKDIR}/node-v${PV}-linux-${NODE_BUILD_ARCH}"

inherit native

do_compile() {
    :
}

# The tarball is already laid out as a prefix, and bin/npm and bin/npx are
# relative symlinks into lib/node_modules; copying wholesale keeps them
# resolving.
do_install() {
    install -d ${D}${prefix}
    cp --preserve=mode,timestamps -R ${S}/bin ${S}/include ${S}/lib ${S}/share ${D}${prefix}/
}
