#!/usr/bin/env bash
# Resolve the meta-wisekiosk HEAD sha on the HOST and write it where bitbake
# will read it as a plain variable (#46).
#
#   tools/write-build-rev.sh
#
# Every route to bitbake that can produce a flashable image runs this first. The
# generated fragment is gitignored: it is build input, not source.
#
# Why the host, and why a file. image-buildinfo reads git live in do_image and
# does not hash what it read, so the commit reaches no task signature and a
# stamp can be replayed while HEAD has moved. Putting the sha in do_image's
# vardeps fixes that, but resolving it INSIDE bitbake does not work here: a
# parse-time `${@git...}` produced a basehash that differed between the cooker
# and the build-time worker reparse. A plain assignment in a conf file has no
# python, no subprocess and no environment to disagree about -- every parse in
# every context reads the same bytes.
#
# The host is also the right authority: the gate compares the image against the
# HOST's HEAD, so that is the value whose movement must force a re-stamp.

set -uo pipefail

cd "$(git rev-parse --show-toplevel)" 2>/dev/null \
    || { printf 'write-build-rev: not inside a git repository\n' >&2; exit 1; }

DEST=meta-wisekiosk/conf/build-rev.inc

rev=$(git rev-parse HEAD 2>/dev/null)
if ! [[ "$rev" =~ ^[0-9a-f]{40}$ ]]; then
    # Refuse rather than write a placeholder. A file saying <unknown> would be a
    # perfectly stable vardep, so the build would succeed and quietly stop
    # re-stamping -- the exact failure this mechanism exists to remove.
    printf 'write-build-rev: cannot resolve HEAD to a 40-character sha (got %s)\n' "${rev:-<nothing>}" >&2
    exit 1
fi

[ -d "$(dirname "$DEST")" ] \
    || { printf 'write-build-rev: %s does not exist -- was the layer renamed?\n' "$(dirname "$DEST")" >&2; exit 1; }

# Rewritten only when the value changes: an unconditional write would touch the
# mtime on every invocation, and bitbake watches conf files for changes.
new="KIOSK_BUILDINFO_REV = \"$rev\""
if [ -f "$DEST" ] && [ "$(tail -n 1 "$DEST")" = "$new" ]; then
    printf 'build rev unchanged: %s\n' "$rev"
    exit 0
fi

{
    printf '# Generated by tools/write-build-rev.sh -- do not edit, do not commit.\n'
    printf '# The meta-wisekiosk commit this build is from. Read by\n'
    printf '# meta-wisekiosk/classes/kiosk-buildinfo-cachesafe.bbclass (#46).\n'
    printf '%s\n' "$new"
} > "$DEST"

printf 'build rev: %s -> %s\n' "$rev" "$DEST"
