#!/usr/bin/env bash
# Resolve the meta-wisekiosk HEAD sha on the HOST and write it where bitbake
# will read it as a plain variable (#46).
#
#   tools/write-build-rev.sh
#
# Every route to bitbake that can produce a flashable image runs this first. The
# generated fragment is gitignored: it is build input, not source.
#
# Read as a plain assignment by
# meta-wisekiosk/classes/kiosk-buildinfo-cachesafe.bbclass.
# See docs/layers-and-kas.md.

set -uo pipefail

cd "$(git rev-parse --show-toplevel)" 2>/dev/null \
    || { printf 'write-build-rev: not inside a git repository\n' >&2; exit 1; }

DEST=meta-wisekiosk/conf/build-rev.inc

rev=$(git rev-parse HEAD 2>/dev/null)
if ! [[ "$rev" =~ ^[0-9a-f]{40}$ ]]; then
    # No placeholder: <unknown> is a stable vardep, so re-stamping would stop
    # silently.
    printf 'write-build-rev: cannot resolve HEAD to a 40-character sha (got %s)\n' "${rev:-<nothing>}" >&2
    exit 1
fi

[ -d "$(dirname "$DEST")" ] \
    || { printf 'write-build-rev: %s does not exist -- was the layer renamed?\n' "$(dirname "$DEST")" >&2; exit 1; }

# Rewritten only when the value changes: an unconditional write would touch the
# mtime on every invocation, and bitbake watches conf files for changes.
new="KIOSK_BUILDINFO_REV = \"$rev\""
if [ -f "$DEST" ] && [ "$(tail -n 1 "$DEST")" = "$new" ]; then
    printf 'build rev unchanged: %s\n' "$rev"
    exit 0
fi

{
    printf '# Generated by tools/write-build-rev.sh -- do not edit, do not commit.\n'
    printf '# The meta-wisekiosk commit this build is from. Read by\n'
    printf '# meta-wisekiosk/classes/kiosk-buildinfo-cachesafe.bbclass (#46).\n'
    printf '%s\n' "$new"
} > "$DEST"

printf 'build rev: %s -> %s\n' "$rev" "$DEST"
